"""
Data models that flow through the agent pipeline.

Pipeline flow:
  Scout → Product → Sourcing → SupplierMatch → Creative → Creative → Launch → LaunchResult
"""

from __future__ import annotations
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum


class AgentStatus(Enum):
    IDLE = "idle"
    SCOUTING = "scouting"
    SOURCING = "sourcing"
    CREATING = "creating"
    LAUNCHING = "launching"
    DONE = "done"
    FAILED = "failed"


@dataclass
class Product:
    """Discovered by the Scout Agent."""
    name: str
    category: str
    daily_sales: int
    conversion_rate: float
    active_competitors: int
    trend_spike_days: int = 7
    source: str = "kalodata"  # kalodata | fastmoss
    discovered_at: datetime = field(default_factory=datetime.now)
    qualities: list[str] = field(default_factory=list)  # wow_factor, solves_problem, easy_content

    @property
    def is_qualified(self) -> bool:
        from config.settings import (
            SCOUT_MIN_DAILY_SALES, SCOUT_MIN_CONVERSION_RATE, SCOUT_MAX_COMPETITORS,
        )
        return (
            self.daily_sales >= SCOUT_MIN_DAILY_SALES
            and self.conversion_rate >= SCOUT_MIN_CONVERSION_RATE
            and self.active_competitors < SCOUT_MAX_COMPETITORS
        )


@dataclass
class SupplierMatch:
    """Found by the Sourcing Agent."""
    product: Product
    supplier_name: str
    ships_from: str
    delivery_days: int
    reliability_score: float
    unit_cost: float
    supplier_url: str = ""

    @property
    def is_valid(self) -> bool:
        from config.settings import (
            SOURCING_SHIP_FROM, SOURCING_MAX_DELIVERY_DAYS, SOURCING_MIN_SUPPLIER_SCORE,
        )
        return (
            self.ships_from == SOURCING_SHIP_FROM
            and self.delivery_days <= SOURCING_MAX_DELIVERY_DAYS
            and self.reliability_score >= SOURCING_MIN_SUPPLIER_SCORE
        )


@dataclass
class Creative:
    """Generated by the Creative Agent."""
    product: Product
    hook: str
    body: str
    cta: str
    tone: str = "game-like"
    reference_ads: list[str] = field(default_factory=list)  # top ad URLs scraped
    follow_up_plan: list[str] = field(default_factory=list)

    @property
    def full_script(self) -> str:
        return f"{self.hook}\n\n{self.body}\n\n{self.cta}"


@dataclass
class LaunchResult:
    """Output of the Launch Agent."""
    product: Product
    supplier: SupplierMatch
    creative: Creative
    shopify_product_id: str | None = None
    seo_title: str = ""
    listing_price: float = 0.0
    profit_margin: float = 0.0
    launched: bool = False
    launched_at: datetime | None = None

    @property
    def is_profitable(self) -> bool:
        from config.settings import LAUNCH_MIN_PROFIT_MARGIN
        return self.profit_margin >= LAUNCH_MIN_PROFIT_MARGIN


@dataclass
class PipelineReport:
    """Summary of a full pipeline run."""
    products_scouted: list[Product] = field(default_factory=list)
    products_qualified: list[Product] = field(default_factory=list)
    suppliers_found: list[SupplierMatch] = field(default_factory=list)
    creatives_generated: list[Creative] = field(default_factory=list)
    launches: list[LaunchResult] = field(default_factory=list)
    started_at: datetime = field(default_factory=datetime.now)
    finished_at: datetime | None = None

    @property
    def success_count(self) -> int:
        return sum(1 for launch in self.launches if launch.launched)
